export const settings = {
  dots: true,
  infinite: true,
  speed: 900,
  autoplay: true,
  autoplaySpeed: 2500,
  slidesToShow: 3,
  slidesToScroll: 1,
  centerMode: true,
  centerPadding: "150px",
  responsive: [
    {
      breakpoint: 1600,
      settings: {
        slidesToShow: 3,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "130px",
      },
    },
    {
      breakpoint: 1500,
      settings: {
        slidesToShow: 3,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "100px",
      },
    },
    {
      breakpoint: 1460,
      settings: {
        slidesToShow: 3,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "50px",
      },
    },
    {
      breakpoint: 1330,
      settings: {
        slidesToShow: 2,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "200px",
      },
    },
    {
      breakpoint: 1290,
      settings: {
        slidesToShow: 2,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "150px",
      },
    },
    {
      breakpoint: 1195,
      settings: {
        slidesToShow: 2,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "100px",
      },
    },
    {
      breakpoint: 1090,
      settings: {
        slidesToShow: 2,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "90px",
      },
    },
    {
      breakpoint: 996,
      settings: {
        slidesToShow: 2,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "50px",
      },
    },
    {
      breakpoint: 947,
      settings: {
        slidesToShow: 2,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "30px",
      },
    },
    {
      breakpoint: 846,
      settings: {
        slidesToShow: 2,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "20px",
      },
    },
    {
      breakpoint: 803,
      settings: {
        slidesToShow: 2,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "10px",
      },
    },
    {
      breakpoint: 740,
      settings: {
        slidesToShow: 2,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "5px",
      },
    },
    {
      breakpoint: 643,
      settings: {
        slidesToShow: 2,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "5px",
      },
    },
    {
      breakpoint: 543,
      settings: {
        slidesToShow: 1,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "120px",
      },
    },
    {
      breakpoint: 506,
      settings: {
        slidesToShow: 1,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "90px",
      },
    },
    {
      breakpoint: 391,
      settings: {
        slidesToShow: 1,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "60px",
      },
    },
    {
      breakpoint: 345,
      settings: {
        slidesToShow: 1,
        infinite: true,
        dots: true,
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: "40px",
      },
    },
  ],
};
